[build]
builder = "nixpacks"
buildCommand = "NODE_ENV=development npm install --no-audit && NODE_ENV=production npm run build"

[deploy]
startCommand = "npx serve -s build --listen tcp://0.0.0.0:$PORT"
